<template>
  <main>
    <div class="main">
      <header class="main-content">
        <div class="box-search">
          <h1>Github user search</h1>

          <input class="search" @change="getData" v-model="term" type="text" placeholder="Search for an user..."
            required />

        </div>
      </header>
    </div>

    <div id="main-content" class="content">
      <div class="img-search">
      </div>
    </div>
    <div class="content" v-show="found">
      <div class="result">
        <div class="card fade-in" v-for="result in filtered" :key="result.name">
          <h4><b>{{ result.login }}</b></h4>
          <div class="img"><img :src="`${result.avatar_url}`" alt="avatar"></div>
          <router-link :to="{name: 'app.user',params: {username:result.login}}"
          >Detalhes</router-link>
        </div>
      </div>
    </div>
    <Paginator :found="found" :page="page" :total="total" @changepage="changePage"/>
  </main>
</template>

<script>
import Paginator from './Paginator.vue';
export default {
  name: "Search",
  data() {
    return {
      term: "",
      results: [],
      found: false,
      total: 0,
      filtered: [],
      per_page: 20,
      page: 1
    }
  },
  components:{
    Paginator
  }, 
  methods: {
    changePage: function(item){
      this.filtered = this.results.slice((item - 1) * this.per_page,(item * this.per_page));
      this.page = item;
    }, 
    async getData() {
      this.found = false;
      this.$axios.get(`https://api.github.com/search/users`, { params: { q: this.term, per_page: 100 } })
        .then((response) => {
          this.results = response.data.items;
          this.total = 100;
          this.found = true;
          this.filtered = this.results.slice(0,this.per_page);
        })
        .catch(function (error) {
          console.error(error);
        });

    }
  }
}
</script>

<style>
.animated-background {
    animation-duration: 1.25s;
    animation-fill-mode: forwards;
    animation-iteration-count: infinite;
    animation-name: placeHolderShimmer;
    animation-timing-function: linear;
    background: #F6F6F6;
    background: linear-gradient(to right, #F6F6F6 8%, #F0F0F0 18%, #F6F6F6 33%);
    background-size: 800px 104px;
    height: 96px;
    position: relative;
}
.main {
  width: 100%;
}

.main-content {
  max-width: calc(1300px - 40px); 
  margin: 0 auto;
}

.main-content h1 {
  font-size: 3em;
  font-family: "Ubuntu";
  text-align: center;
  padding: 20px 0;
  font-weight: 500;

}
.box-search{
      max-width: 900px;
    margin: 0 auto;
}
.search[type=text] {
  width: calc(100% - 80px);
  margin: 0 40px;
  padding: 10px 10px !important;
  font-size: 1.4em;



}

.search[type=text]:focus {
  border-color: #9dbbcf;
  box-shadow: 0 0 0 0.2rem rgba(40, 139, 206, 0.25);
  border-color: -internal-light-dark(rgb(211, 32, 32), rgb(214, 2, 2));
}

.content {
  max-width: calc(1300px - 80px);
  margin: 0 auto;
  border: 1px solid #eaeaea;
  padding: 5px 10px !important;
}

.result {
  max-width: calc(1300px - 40px);
  /* padding: 0 20px; */
  margin: 0 auto;
  display: flex;
  justify-content: space-around;
  flex-wrap: wrap;
}

.card {
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
  transition: 0.3s;
  flex-basis: calc(25% - 20px);
  margin-bottom: 10px;
}

.card h4 {
  background-color: #2980b9;
  margin: 0;
  font-size: 15px;
  padding-bottom: 10px;
  padding-top: 10px;
  padding-left: 10px;
  color: #fff;
  font-weight: 500;
  text-align: center;
}

.img {
  padding: 10px;
}

.result img,
.result-flw img {
  width: 100%;
  border-radius: 50%;
  -moz-border-radius: 50%;
  -webkit-border-radius: 50%;
  padding: 3px;
  background-color: #2980b9;
  margin: 0 auto;
}

.fade-in {
  -webkit-animation: fade-in 1.2s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
  animation: fade-in 1.2s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2022-6-5 20:15:20
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation fade-in
 * ----------------------------------------
 */
@-webkit-keyframes fade-in {
  0% {
    opacity: 0;
  }

  100% {
    opacity: 1;
  }
}

@keyframes fade-in {
  0% {
    opacity: 0;
  }

  100% {
    opacity: 1;
  }
}

@media (max-width: 30em) {
  .main-content h1{
    font-size: 2em;
  }
  .main-header-content h1 {
    font-size: 1.4em;
  }
  .card{
    flex-basis: calc(50% - 20px);;
  }
}
</style>